val smallcfg = makecfg (fn (ctrlname, path) => {
      xsep           = 4,
      ysep           = 4,
      ctrlfontheight = 10,
      ctrlcharwidth  = 7,
      namefontheight = 10,
      namecharwidth  = 7,
      sitefontheight = 10,
      sitecharwidth  = 7,
      textmargin     = 2,
      textysep       = 3,
      edgeysep       = 14,
      idleedgelength = 8,
      rootwidth      = 40,
      rootheight     = 30,
      rootrounding   = 5,
      nodeminwidth   = Int.max (30, Int.* (7, size ctrlname)),
      nodeminheight  = 25,
      labelpos       = BG.PPSVG.SW,
      portsep        = 7,
      binderradius   = 3,
      sitewidth      = 30,
      siteheight     = 10,
      siterounding   = 5
  })
