(*******************************)
(*     String Declarations     *)
(*******************************)
val Process        = "Process"
val Instance       = "Instance"
val Scope          = "Scope"
val ActiveScope    = "ActiveScope"
val Run            = "Run"
(* val Running        = "Running" *)
val Invoked        = "Invoked"
 val Stopped        = "Stopped" 
(* val Stop           = "Stop" *)
(* val Variables      = "Variables" *)
val Var            = "Var"
(* val Variable       = "Variable" *)
(* val VariableRef    = "VariableRef" *)
val Ref            = "Ref"
(* val Sequence       = "Sequence" *)
val Next           = "Next"
(* val Flow           = "Flow" *)
val While          = "While"
val If             = "If"
val Cond           = "Cond"
(* val Condition      = "Condition" *)
val Then           = "Then"
val Else           = "Else"
val True           = "True"
val False          = "False"
val Ass            = "Ass"
(* val Assign         = "Assign" *)
(* val Copy           = "Copy" *)
(* val To             = "To" *)
(* val From           = "From" *)
(* val ToPLink        = "ToPLink" *)
(* val FromPLink      = "FromPLink" *)
val Inv            = "Inv"
(* val Invoke            = "Invoke" *)
val PartnerLinks   = "PartnerLinks"    
val PartnerLink    = "PartnerLink"
val Mess           = "Mess"
(* val Message        = "Message" *)
val Link           = "Link"
val CrInst         = "CrInst"
(* val CreateInstance = "CreateInstance" *)
val Rec            = "Rec"
val Rep            = "Rep"
val Reply          = "Reply"
val GetRep         = "GetRep"
val Exit           = "Exit"

(*    For names                *)
val id                         = "id"
(*val inst_id                    = "inst_id"
val inst_id1                   = "inst_id1"
val inst_id2                   = "inst_id2" *)
val id1                        = "id1"
val id2                        = "id2"
(* val inst_id_invoker            = "inst_id_invoker" *)
(* val inst_id_invoked            = "inst_id_invoked" *)
(* val inst_id_invoked1           = "inst_id_invoked1" *)
(* val inst_id_invoked2           = "inst_id_invoked2" *)
(* val scope                      = "scope" *)
(* val scope1                     = "scope1" *)
(* val scope2                     = "scope2" *)
val scf                        = "scf"
val sct                        = "sct"
val f                          = "f"
val t                          = "t"
val proc_name                  = "proc_name"
(* val var                        = "var" *)
val n                          = "n"
val m                          = "m"
(* val var_scope                  = "var_scope" *)
val sc                         = "sc"
val outvar                     = "outvar"
val outvar_scope               = "outvar_scope"
val invar                      = "invar"
val invar_scope                = "invar_scope"
val oper                       = "oper"
val partner_link               = "partner_link"
val partner_link_invoker       = "partner_link_invoker"
val partner_link_invoked       = "partner_link_invoked"
val partner_link_scope         = "partner_link_scope"
val partner_link_scope_invoker = "partner_link_scope_invoker"
val partner_link_scope_invoked = "partner_link_scope_invoked"
val echo                       = "echo"
val echo_id                    = "echo_id"
val echo_process               = "echo_process"
val echo_value                 = "echo_value"
val echo_service               = "echo_service"
val echo_client                = "echo_client"
val s                          = "s"
val s'                         = "s'"
val s1                         = "s1"
val s2                         = "s2"
val s3                         = "s3"
val x                          = "x"
val y                          = "y"
val z                          = "z"
val v                          = "v"
val caller                     = "caller"
val caller_id                  = "caller_id"
val p                          = "p"
val p1                         = "p1"
val p2                         = "p2"
val p3                         = "p3"
val p4                         = "p4"
val p5                         = "p5"
(*
val pred                       = "pred"
val pred1                      = "pred1"
val pred2                      = "pred2"
val pred3                      = "pred3"
val pred4                      = "pred4"
val pred5                      = "pred5"
*)
val succ                       = "succ"
val succ1                      = "succ1"
val succ2                      = "succ2"

val l                          = "l"
val lsc                        = "lsc"
val l1                         = "l1"
val l1sc                       = "l1sc"
val l2                         = "l2"
val l2sc                       = "l2sc"
val vsc                        = "vsc"

val v2                         = "v2"
val v2sc                       = "v2sc"
val v1                         = "v1"
val v1sc                       = "v1sc"

