val smallcfg = makecfg (fn (ctrlname, path) => {
      xsep           = 4,
      ysep           = 4,
      ctrlfontheight = 12,
      ctrlcharwidth  = 8,
      namefontheight = 10,
      namecharwidth  = 7,
      sitefontheight = 12,
      sitecharwidth  = 8,
      textmargin     = 2,
      textysep       = 3,
      edgeysep       = 22,
      idleedgelength = 8,
      rootwidth      = 40,
      rootheight     = 30,
      rootrounding   = 5,
      nodeminwidth   = Int.max (30, Int.* (8, size ctrlname)),
      nodeminheight  = 25,
      labelpos       = case path of 0 :: _ => BG.PPSVG.SE | _ => BG.PPSVG.SW,
      portsep        = 7,
      binderradius   = 3,
      sitewidth      = 30,
      siteheight     = 10,
      siterounding   = 5
  })
